name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy'
        required: false
        type: string
        default: 'latest'
      environment:
        description: 'Deployment environment (e.g., dev, staging, production)'
        required: false
        type: string
        default: 'production'
    secrets:
      GHCR_PAT:
        description: 'GitHub Container Registry Personal Access Token'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        if: ${{ secrets.GHCR_PAT != '' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Deploy application
        run: |
          echo "Deploying to ${{ inputs.environment }} environment"
          echo "Using image tag: ${{ inputs.image_tag }}"
          # Add your deployment logic here
          # This is a placeholder for actual deployment steps
